data:
  data_dir: "pix2code_project/data"
  max_samples: 100
  batch_size: 8
  num_workers: 0

model:
  vocab_size: 5000
  embedding_dim: 256
  lstm_units: 256
  attention_units: 256

training:
  learning_rate: 0.0003
  weight_decay: 0.01
  epochs: 150
  batch_size: 8
  min_lr: 1e-6
  output_dir: "pix2code_project/results"
  num_workers: 0

visual_encoder:
  model_name: "resnet50"
  pretrained: true
  freeze_backbone: false

layout_processor:
  hidden_size: 256
  num_attention_heads: 8
  dropout: 0.1

code_decoder:
  model_name: "gpt2" 